name: Build QEMU with Remote-Port Support

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout QEMU Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            build-essential \
            pkg-config \
            libglib2.0-dev \
            libpixman-1-dev \
            zlib1g-dev \
            libfdt-dev \
            ninja-build \
            python3 \
            python3-pip \
            libsystemc-dev \
            libbz2-dev \
            libzstd-dev \
            libpng-dev \
            libjpeg-dev \
            libselinux1-dev \
            libncurses-dev \
            libgcrypt20-dev \
            libmount-dev \
            libblkid-dev \
            autoconf \
            automake \
            gettext \
            wget



      - name: Build util-linux (Fallback if libmount.a Missing)
        run: |
          if [ ! -f /usr/lib/x86_64-linux-gnu/libmount.a ]; then
            wget https://github.com/util-linux/util-linux/archive/refs/tags/v2.38.tar.gz
            tar -xzf v2.38.tar.gz
            cd util-linux-2.38
            if [ ! -f configure ]; then
              ./autogen.sh || { echo "autogen.sh failed"; exit 1; }
            fi
            ./configure --prefix=/usr/local --enable-static
            make -j$(nproc)
            sudo make install
            cd ..
          fi
        continue-on-error: true

    

      - name: Configure QEMU
        run: |
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
          export PKG_CONFIG_LIBMOUNT_STATIC=false
          ./configure \
            --target-list=arm-softmmu,aarch64-softmmu \
            --enable-system \
            --enable-trace-backends=simple \
            --enable-vnc \
            --enable-curses \
            --enable-libgcrypt \
            --enable-zstd \
            --enable-bzip2 \
            --enable-png \
            --enable-vnc-jpeg \
            --enable-virtfs \
            --prefix=$PWD/install \
            --static \
            || { cat config.log; exit 1; }
        env:
          CFLAGS: -O2 -g
          LDFLAGS: -O2 -Wl,-z,relro -Wl,-z,now -Wl,--warn-common

      - name: Build QEMU
        run: make -j$(nproc)

      - name: Install QEMU
        run: make install

      - name: Verify Remote-Port and VirtFS Support
        run: |
          ./install/bin/qemu-system-arm -device help | grep remote-port || exit 1
          ./install/bin/qemu-system-aarch64 -device help | grep remote-port || exit 1
          ./install/bin/qemu-system-arm -device help | grep virtio-9p || exit 1
          ./install/bin/qemu-system-aarch64 -version
          ./install/bin/qemu-system-arm -version

      - name: Package Artifacts
        run: |
          tar -czf qemu-binaries.tar.gz -C install/bin qemu-system-arm qemu-system-aarch64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qemu-binaries
          path: qemu-binaries.tar.gz
          retention-days: 7
